language: php

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini

before_script:
    - composer install

script: |
    ./vendor/bin/simple-phpunit

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3
        - php: 7.4
    fast_finish: true
